#! ---------------------------------------------------------------
#! Aurora Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By Benny Guo
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#！ @docs https://aurora.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  subtitle: sonya's Blog
  author: sonyakun
  nick: 
  description: 
  link: '/'
  language: en
  multi_language: true
  logo: 
  avatar: https://drive.google.com/uc?export=view&id=1xAPvLj67mI3nAllt2baVl_S1tvE37WzB
  beian:
    number: ''
    link: ''
  police_beian:
    number: ''
    link: ''
  # Start date of the blog YYY-MM-DD
  # 博客开始运行日期
  started_date:
  # Path unique identifier (文章 URL 唯一标识)
  # uid: use unique ID
  # slug: use generated slug base on title
  # (Default is 'slug')
  pathSlug: 'slug'

#! ---------------------------------------------------------------
#! Authors Configs
#！ @docs https://aurora.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  sonyakun:
    name: sonyakun
    avatar: https://drive.google.com/uc?export=view&id=1xAPvLj67mI3nAllt2baVl_S1tvE37WzB
    link: https://misskey.io/@sonyakun
    description: '興味を持ったものをやってみる人(?)'
    socials:
      github: https://github.com/sonyakun

#! ---------------------------------------------------------------
#! Menu Configs
#！ @docs https://aurora.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  About: true
  Tags: true
  Archives: true
  Friends: false

#! ---------------------------------------------------------------
#! Theme Config
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
theme:
  dark_mode: 'auto'
  profile_shape: circle # support `circle`, `diamond`, `rounded`
  feature: true
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

#! ---------------------------------------------------------------
#! Social Configs
#! @docs https://aurora.tridiamond.tech/guide/social.html
#! ---------------------------------------------------------------
socials:
  github: 'https://github.com/sonyakun'
  twitter: 'https://twitter.com/sonyakun1'

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------
site_meta:
  cdn: cn
  favicon:
  description: 'sonyakunが思ったことをいろいろ書きます'
  keywords: ' tech, idea'
  author: 'sonyakun'

#! ---------------------------------------------------------------
#! Plugins
#! @docs https://aurora.tridiamond.tech/guide/plugins.html
#! ---------------------------------------------------------------

# For local development only!
gitalk:
  enable: false
  autoExpand: true
  clientID: ''
  clientSecret: ''
  repo: '' ## dev-blo-comments
  owner: '' ## owner name
  admin: [''] ## ['admin_name']
  id: uid
  language: en
  distractionFreeMode: true
  recentComment: true
  proxy: ''

# Valine comment plugin (recommended!)
# see https://valine.js.org/quickstart.html
valine:
  enable: false
  app_id:
  app_key:
  avatar: ''
  placeholder: Leave your thoughts behind~
  visitor: true
  lang: en
  avatarForce: false
  meta: ['nick']
  requiredFields: ['nick']
  admin: 'sonyakun' # admin username
  recentComment: true

# Twikoo comment plugin
# see https://twikoo.js.org/quick-start.html
twikoo:
  enable: false
  recentComment: true
  envId: xxxxxxxxxxxxxxx # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  # region: ap-guangzhou # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
  lang: 'en' # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js

# Waline comment plugin
# see https://waline.js.org/guide/get-started/
waline:
  enable: true
  recentComment: true
  reaction: false
  login: 'disable'
  meta: ['nick']
  requiredMeta: ['nick']
  commentSorting: 'latest'
  wordLimit: 0
  imageUploader: false
  pageSize: 10
  serverURL: 'https://waline-mu-peach.vercel.app/' # 填写服务端地址

# Enable Busuanzi statistic plugin
# see http://ibruce.info/2015/04/04/busuanzi/
busuanzi:
  enable: false

copy_protection:
  enable: true
  author:
    ja: 作者
    cn: 作者
    en: Author
  link:
    ja: 記事はこちらから
    cn: 本文来自于
    en: Article is from
  license:
    ja: このWebサイトのコンテンツは表示 - 非営利 - 継承 4.0 国際 (CC-BY-NC-SA 4.0)に基づいて自由に利用可能です
    cn: 博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议
    en: This content is shared under the CC BY-NC-SA 4.0 protocol (Non-Commercial)

#! ---------------------------------------------------------------
#! Enable Aurora Bot Dia
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
aurora_bot:
  enable: false
  locale: en
  bot_type: dia
  tips:

#! ---------------------------------------------------------------
#! Injections
#! @docs https://aurora.tridiamond.tech/guide/site-meta.html#custom-meta
#! ---------------------------------------------------------------
injects:
  scripts:
  css:

#! ---------------------------------------------------------------
#! Footer links
#! ---------------------------------------------------------------
footer_links:
  - title: # main title
    links:
      - title: Misskey.io # link title
        url: https://misskey.io/@sonyakun # URL link
      - title: RSS # link title
        url: https://blog.sonyakun.com/atom.xml # URL link
      # - title: Friends # link of friends mode / 友链模式
      #   mode: 'links'

#! ---------------------------------------------------------------
#! Highlighter Shiki
#! ---------------------------------------------------------------
shiki:
  enable: true
  backgroundColor: "#1a1a1a"

